spring:
  datasource:
    url: jdbc:mysql://localhost/test2?characterEncoding=utf8&serverTimezone=GMT%2b0&useLegacyDatetimeCode=false
    username: root
    password: 123456
#    url: jdbc:postgresql://localhost:5432/test2
#    username: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update

server:
  port: 1023

aptos:
  contract:
    address:
      "0x2239450816c09cef0202c090ec15f648a33e3fff0209167cad1ef6830b1d5d1f"
    node-api:
      base-url: "https://fullnode.devnet.aptoslabs.com/v1"
#    pull-day-summary-events:
#      day-summary-created:
#        fixed-delay: 6000
#    pull-order-v2-events:
#      order-v2-created:
#        fixed-delay: 6000
